In [101]:
import numpy as np

In [102]:
arra = list(range(1,10))
arra

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [103]:
array1 = np.array([(1,2,3),(4,5,6)])
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [104]:
array2 = np.array([(1.2,2,3),(4.6,5,6)])
array2

array([[1.2, 2. , 3. ],
       [4.6, 5. , 6. ]])

In [105]:
array1.dtype

dtype('int32')

In [106]:
array2.dtype

dtype('float64')

In [107]:
array4 = np.zeros((2,3))
array4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [108]:
array5 = np.ones((2,3))
array5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [109]:
array6 = np.arange(10,30,5)
array6

array([10, 15, 20, 25])

In [110]:
array7 = np.random.rand(2,3)
array7

array([[0.71270517, 0.96330177, 0.32257459],
       [0.16956946, 0.50330889, 0.3833829 ]])

In [111]:
array2 - 1

array([[0.2, 1. , 2. ],
       [3.6, 4. , 5. ]])

In [112]:
array8 = np.array([(1,2,3),(4,5,6),(7,8,9)])
array8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Slice

In [113]:
array8[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
array2.reshape((3,2))

array([[1.2, 2. ],
       [3. , 4.6],
       [5. , 6. ]])

In [115]:
narray = np.split(array8,3)
narray

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [116]:
arrayj = np.concatenate(narray)
arrayj

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [117]:
array2

array([[1.2, 2. , 3. ],
       [4.6, 5. , 6. ]])

In [118]:
array2.max()

6.0

In [119]:
array2.min()

1.2

In [120]:
array2.sum()

21.8

In [121]:
array2.mean()

3.6333333333333333

In [122]:
import pandas as pd

In [123]:
vingadores = ["thor","hulk","iron man","black panther", "captain USA"]
vingadores

['thor', 'hulk', 'iron man', 'black panther', 'captain USA']

In [124]:
type(vingadores)

list

In [125]:
serie_vingadores = pd.Series(vingadores)
serie_vingadores

0             thor
1             hulk
2         iron man
3    black panther
4      captain USA
dtype: object

In [126]:
type(serie_vingadores)

pandas.core.series.Series

In [127]:
array_vingadores = np.array(vingadores)
array_vingadores

array(['thor', 'hulk', 'iron man', 'black panther', 'captain USA'],
      dtype='<U13')

In [128]:
array_serie = serie_vingadores.to_numpy()
array_serie

array(['thor', 'hulk', 'iron man', 'black panther', 'captain USA'],
      dtype=object)

## Atividade: Fusão
### ➔ O QUE FAZER?
Escrever um código.
### ➔ COMO FAZER?
1. Crie um array numpy com os números [10 20 30 40 50 60 70];
2. Subtraia 5 de todos os números do array e reatribua no array original. Veja o tipo dos elementos
no array antes e depois dessa operação;
3. Converta o array para uma series do pandas;

In [129]:
array_numpy = np.array([10,20,30,40,50,60,70])
array_numpy

array([10, 20, 30, 40, 50, 60, 70])

In [130]:
array_numpy = array_numpy - 5
array_numpy

array([ 5, 15, 25, 35, 45, 55, 65])

In [131]:
array_pandas = pd.Series(array_numpy)
array_pandas

0     5
1    15
2    25
3    35
4    45
5    55
6    65
dtype: int32