In [11]:
import pandas as pd
import numpy as np

In [12]:
array1 = np.array([[0,1,2],[3,4,5]])
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [13]:
dataframe1 = pd.DataFrame(array1, columns=['col1','col2','col3'])
dataframe1

col1  col2  col3
0     0     1     2
1     3     4     5

In [14]:
pop_data = {'Flamengo': [56,72,90,71, 71],
        'Palmeiras': [63, 80,74,58,66],
        'Corinthians': [72, 44,56,51,57]}

futebol = pd.DataFrame(pop_data, index=[2017,2018,2019,2020,2021])
futebol

Flamengo  Palmeiras  Corinthians
2017        56         63           72
2018        72         80           44
2019        90         74           56
2020        71         58           51
2021        71         66           57

In [15]:
futebol['Flamengo']

2017    56
2018    72
2019    90
2020    71
2021    71
Name: Flamengo, dtype: int64

In [16]:
futebol.values

array([[56, 63, 72],
       [72, 80, 44],
       [90, 74, 56],
       [71, 58, 51],
       [71, 66, 57]], dtype=int64)

In [17]:
futebol['Flamengo'].values

array([56, 72, 90, 71, 71], dtype=int64)

In [18]:
futebol['Flamengo'].value_counts()

71    2
56    1
72    1
90    1
Name: Flamengo, dtype: int64

Adciononando uma nova coluna

In [19]:
futebol['nova'] = np.NaN
futebol

Flamengo  Palmeiras  Corinthians  nova
2017        56         63           72   NaN
2018        72         80           44   NaN
2019        90         74           56   NaN
2020        71         58           51   NaN
2021        71         66           57   NaN

Faz um transpoisição, Linha vira Coluna e vice-versa

In [20]:
futebol.T

2017  2018  2019  2020  2021
Flamengo     56.0  72.0  90.0  71.0  71.0
Palmeiras    63.0  80.0  74.0  58.0  66.0
Corinthians  72.0  44.0  56.0  51.0  57.0
nova          NaN   NaN   NaN   NaN   NaN