In [148]:
import pandas as pd
import numpy as np

[Documentação](https://pandas.pydata.org/pandas-docs/version/0.21/generated/pandas.DataFrame.html)

In [149]:
array1 = np.array([[0,1,2],[3,4,5]])
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [150]:
dataframe1 = pd.DataFrame(array1, columns=['col1','col2','col3'])
dataframe1

col1  col2  col3
0     0     1     2
1     3     4     5

In [151]:
pop_data = {'Flamengo': [56,72,90,71, 71],
        'Palmeiras': [63, 80,74,58,66],
        'Corinthians': [72, 44,56,51,57]}

futebol = pd.DataFrame(pop_data, index=[2017,2018,2019,2020,2021])
futebol

Flamengo  Palmeiras  Corinthians
2017        56         63           72
2018        72         80           44
2019        90         74           56
2020        71         58           51
2021        71         66           57

In [152]:
futebol['Flamengo']

2017    56
2018    72
2019    90
2020    71
2021    71
Name: Flamengo, dtype: int64

In [153]:
futebol.values

array([[56, 63, 72],
       [72, 80, 44],
       [90, 74, 56],
       [71, 58, 51],
       [71, 66, 57]], dtype=int64)

In [154]:
futebol['Flamengo'].values

array([56, 72, 90, 71, 71], dtype=int64)

In [155]:
futebol['Flamengo'].value_counts()

71    2
56    1
72    1
90    1
Name: Flamengo, dtype: int64

Adciononando uma nova coluna

In [156]:
futebol['nova'] = np.NaN
futebol

Flamengo  Palmeiras  Corinthians  nova
2017        56         63           72   NaN
2018        72         80           44   NaN
2019        90         74           56   NaN
2020        71         58           51   NaN
2021        71         66           57   NaN

Faz um transpoisição, Linha vira Coluna e vice-versa

In [157]:
futebol.T

2017  2018  2019  2020  2021
Flamengo     56.0  72.0  90.0  71.0  71.0
Palmeiras    63.0  80.0  74.0  58.0  66.0
Corinthians  72.0  44.0  56.0  51.0  57.0
nova          NaN   NaN   NaN   NaN   NaN

Renomear Coluna

In [158]:
futebol.rename(columns={'nova':'CAM'})

Flamengo  Palmeiras  Corinthians  CAM
2017        56         63           72  NaN
2018        72         80           44  NaN
2019        90         74           56  NaN
2020        71         58           51  NaN
2021        71         66           57  NaN

Esses dados nao vao ser salvos >>

In [159]:
futebol

Flamengo  Palmeiras  Corinthians  nova
2017        56         63           72   NaN
2018        72         80           44   NaN
2019        90         74           56   NaN
2020        71         58           51   NaN
2021        71         66           57   NaN

Renomer salvando os novos dados

In [160]:
futebol = futebol.rename(columns={'nova':'CAM'})
futebol

Flamengo  Palmeiras  Corinthians  CAM
2017        56         63           72  NaN
2018        72         80           44  NaN
2019        90         74           56  NaN
2020        71         58           51  NaN
2021        71         66           57  NaN

In [161]:
futebol.rename(columns={'CAM':'Atletico'}, inplace=True)
futebol

Flamengo  Palmeiras  Corinthians  Atletico
2017        56         63           72       NaN
2018        72         80           44       NaN
2019        90         74           56       NaN
2020        71         58           51       NaN
2021        71         66           57       NaN

In [162]:
futebol['Flamengo2'] = futebol['Flamengo']*2
futebol

Flamengo  Palmeiras  Corinthians  Atletico  Flamengo2
2017        56         63           72       NaN        112
2018        72         80           44       NaN        144
2019        90         74           56       NaN        180
2020        71         58           51       NaN        142
2021        71         66           57       NaN        142

Descrever os dados das colunas

In [163]:
futebol.describe()

Flamengo  Palmeiras  Corinthians  Atletico   Flamengo2
count   5.000000   5.000000     5.000000       0.0    5.000000
mean   72.000000  68.200000    56.000000       NaN  144.000000
std    12.062338   8.786353    10.319884       NaN   24.124676
min    56.000000  58.000000    44.000000       NaN  112.000000
25%    71.000000  63.000000    51.000000       NaN  142.000000
50%    71.000000  66.000000    56.000000       NaN  142.000000
75%    72.000000  74.000000    57.000000       NaN  144.000000
max    90.000000  80.000000    72.000000       NaN  180.000000

Soma o valor por coluna

In [164]:
futebol.sum()

Flamengo       360.0
Palmeiras      341.0
Corinthians    280.0
Atletico         0.0
Flamengo2      720.0
dtype: float64

Soma pela linha

In [165]:
futebol.sum(axis='columns')

2017    303.0
2018    340.0
2019    400.0
2020    322.0
2021    336.0
dtype: float64

In [166]:
futebol.mean()

Flamengo        72.0
Palmeiras       68.2
Corinthians     56.0
Atletico         NaN
Flamengo2      144.0
dtype: float64

In [167]:
futebol.median()

Flamengo        71.0
Palmeiras       66.0
Corinthians     56.0
Atletico         NaN
Flamengo2      142.0
dtype: float64

In [168]:
futebol.min()

Flamengo        56.0
Palmeiras       58.0
Corinthians     44.0
Atletico         NaN
Flamengo2      112.0
dtype: float64

In [169]:
futebol.max()

Flamengo        90.0
Palmeiras       80.0
Corinthians     72.0
Atletico         NaN
Flamengo2      180.0
dtype: float64

In [170]:
futebol.isnull()

Flamengo  Palmeiras  Corinthians  Atletico  Flamengo2
2017     False      False        False      True      False
2018     False      False        False      True      False
2019     False      False        False      True      False
2020     False      False        False      True      False
2021     False      False        False      True      False

### Criar um DataFrame com duas linhas e duas colunas de valores inteiros; (1,2,3,4) colunas 1 e coluna 2 como rótulo de coluna

- Depois de criado, atualizar os valores da primeira coluna multiplicando os valores existentes por 2”;

- Criar uma nova coluna com todos os valores nulos.

In [171]:
pop_data = {'col1': [1,2,3,4],
        'col2': [1,2,3,4]}

data = pd.DataFrame(pop_data)
data

col1  col2
0     1     1
1     2     2
2     3     3
3     4     4

In [172]:
data['col1'] = data['col1']*2
data

col1  col2
0     2     1
1     4     2
2     6     3
3     8     4

In [173]:
data['col3'] = np.NaN
data

col1  col2  col3
0     2     1   NaN
1     4     2   NaN
2     6     3   NaN
3     8     4   NaN

In [174]:
futebol['nova'] = np.NaN

In [175]:
futebol.drop(["nova"], axis=1, inplace=True)
futebol

Flamengo  Palmeiras  Corinthians  Atletico  Flamengo2
2017        56         63           72       NaN        112
2018        72         80           44       NaN        144
2019        90         74           56       NaN        180
2020        71         58           51       NaN        142
2021        71         66           57       NaN        142

### Matrizes

In [ ]:
notas_data = {'Matematica': [6,5,5],
        'Fisisca': [4,7,6],
        'Quimica':[5,5,7],
        'Biologia':[8,5,4]}

nota = pd.DataFrame(notas_data)
nota