In [69]:
import pandas as pd
import numpy as np

In [70]:
array1 = np.array([[0,1,2],[3,4,5]])
array1

array([[0, 1, 2],
       [3, 4, 5]])

In [71]:
dataframe1 = pd.DataFrame(array1, columns=['col1','col2','col3'])
dataframe1

col1  col2  col3
0     0     1     2
1     3     4     5

In [72]:
pop_data = {'Flamengo': [56,72,90,71, 71],
        'Palmeiras': [63, 80,74,58,66],
        'Corinthians': [72, 44,56,51,57]}

futebol = pd.DataFrame(pop_data, index=[2017,2018,2019,2020,2021])
futebol

Flamengo  Palmeiras  Corinthians
2017        56         63           72
2018        72         80           44
2019        90         74           56
2020        71         58           51
2021        71         66           57

In [73]:
futebol['Flamengo']

2017    56
2018    72
2019    90
2020    71
2021    71
Name: Flamengo, dtype: int64

In [74]:
futebol.values

array([[56, 63, 72],
       [72, 80, 44],
       [90, 74, 56],
       [71, 58, 51],
       [71, 66, 57]], dtype=int64)

In [75]:
futebol['Flamengo'].values

array([56, 72, 90, 71, 71], dtype=int64)

In [76]:
futebol['Flamengo'].value_counts()

71    2
56    1
72    1
90    1
Name: Flamengo, dtype: int64

Adciononando uma nova coluna

In [77]:
futebol['nova'] = np.NaN
futebol

Flamengo  Palmeiras  Corinthians  nova
2017        56         63           72   NaN
2018        72         80           44   NaN
2019        90         74           56   NaN
2020        71         58           51   NaN
2021        71         66           57   NaN

Faz um transpoisição, Linha vira Coluna e vice-versa

In [78]:
futebol.T

2017  2018  2019  2020  2021
Flamengo     56.0  72.0  90.0  71.0  71.0
Palmeiras    63.0  80.0  74.0  58.0  66.0
Corinthians  72.0  44.0  56.0  51.0  57.0
nova          NaN   NaN   NaN   NaN   NaN

Renomear Coluna

In [79]:
futebol.rename(columns={'nova':'CAM'})

Flamengo  Palmeiras  Corinthians  CAM
2017        56         63           72  NaN
2018        72         80           44  NaN
2019        90         74           56  NaN
2020        71         58           51  NaN
2021        71         66           57  NaN

Esses dados nao vao ser salvos >>

In [80]:
futebol

Flamengo  Palmeiras  Corinthians  nova
2017        56         63           72   NaN
2018        72         80           44   NaN
2019        90         74           56   NaN
2020        71         58           51   NaN
2021        71         66           57   NaN

Renomer salvando os novos dados

In [81]:
futebol = futebol.rename(columns={'nova':'CAM'})
futebol

Flamengo  Palmeiras  Corinthians  CAM
2017        56         63           72  NaN
2018        72         80           44  NaN
2019        90         74           56  NaN
2020        71         58           51  NaN
2021        71         66           57  NaN

In [82]:
futebol.rename(columns={'CAM':'Atletico'}, inplace=True)
futebol

Flamengo  Palmeiras  Corinthians  Atletico
2017        56         63           72       NaN
2018        72         80           44       NaN
2019        90         74           56       NaN
2020        71         58           51       NaN
2021        71         66           57       NaN

In [83]:
futebol['Flamengo2'] = futebol['Flamengo']*2
futebol

Flamengo  Palmeiras  Corinthians  Atletico  Flamengo2
2017        56         63           72       NaN        112
2018        72         80           44       NaN        144
2019        90         74           56       NaN        180
2020        71         58           51       NaN        142
2021        71         66           57       NaN        142

Descrever os dados das colunas

In [84]:
futebol.describe()

Flamengo  Palmeiras  Corinthians  Atletico   Flamengo2
count   5.000000   5.000000     5.000000       0.0    5.000000
mean   72.000000  68.200000    56.000000       NaN  144.000000
std    12.062338   8.786353    10.319884       NaN   24.124676
min    56.000000  58.000000    44.000000       NaN  112.000000
25%    71.000000  63.000000    51.000000       NaN  142.000000
50%    71.000000  66.000000    56.000000       NaN  142.000000
75%    72.000000  74.000000    57.000000       NaN  144.000000
max    90.000000  80.000000    72.000000       NaN  180.000000